Repository 0silverback0/LandingPages, pull requests merged in 2023-10, with the labels that each got.

#2 Added correct style in header image and made it responsive
  EarWorms/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#3 Hacktoberfest
  Lioness/assets/lion.png
  Lioness/assets/lioness.png
  Lioness/css/styles.css
  Lioness/index.html
  Lioness/js/script.js
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#4 Watch Landing Page
  Animated Landing page/images/icon1.png
  Animated Landing page/images/icon2.png
  Animated Landing page/images/icon3.png
  Animated Landing page/images/logow.png
  Animated Landing page/images/twitter.png
  Animated Landing page/images/wat3.png
  Animated Landing page/index.html
  Animated Landing page/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#6 portfolio landing
  Portfolio/crop.avif
  Portfolio/index.html
  Portfolio/max-duzij-qAjJk-un3BI-unsplash.jpg
  Portfolio/script.js
  Portfolio/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#7 added details section to EarWorms
  EarWorms/index.html
  EarWorms/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#8 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#9 feat: add landing page codebuddy
  CodeBuddy/.gitignore
  CodeBuddy/dist/output.css
  CodeBuddy/package-lock.json
  CodeBuddy/package.json
  CodeBuddy/src/codebuddy-logo.png
  CodeBuddy/src/dropdown-menu.js
  CodeBuddy/src/index.html
  CodeBuddy/src/input.css
  CodeBuddy/tailwind.config.js
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#15 Updated Home tab Links
  Animated Landing page/index.html
  CodeBuddy/src/index.html
  CodeBuddy/yarn.lock
  EarWorms/index.html
  Lioness/index.html
  Portfolio/index.html
  node_modules/.yarn-integrity
  yarn.lock
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#17 Updated the Home tab links
  Animated Landing page/index.html
  EarWorms/index.html
  Portfolio/index.html
  index.html
  pexels-sk-814136.jpg
  styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#16 Books store LandingPage
  .vscode/settings.json
  Books_store_LandingPage/index.html
  Books_store_LandingPage/script.js
  Books_store_LandingPage/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#31 Created the contact page for issue EarWorms page
  EarWorms/contact.css
  EarWorms/contact.html
  EarWorms/index.html
Labels: enhancement, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#32 added GymsoWebsite Landing Page
  gymsoWebsite/Images/bg.jpg
  gymsoWebsite/Images/class1.jpg
  gymsoWebsite/Images/class2.jpg
  gymsoWebsite/Images/class3.jpg
  gymsoWebsite/Images/team1.jpg
  gymsoWebsite/Images/team2.jpg
  gymsoWebsite/index.html
  gymsoWebsite/script.js
  gymsoWebsite/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#39 Change title and add favicon
  favicon/android-chrome-192x192.png
  favicon/android-chrome-512x512.png
  favicon/apple-touch-icon.png
  favicon/favicon-16x16.png
  favicon/favicon-32x32.png
  favicon/favicon.ico
  favicon/site.webmanifest
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#45 made the landing page responsive and improved the navbar
  Animated Landing page/index.html
  Animated Landing page/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#46 Added a New Landing Page Called: Personal Site
  .DS_Store
  Personal_Site/header.jpeg
  Personal_Site/index.html
  Personal_Site/profile.jpeg
  Personal_Site/style.css
  Personal_Site/typing.gif
  index.html
  node_modules/.package-lock.json
  package-lock.json
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#51 feat: added animated hover effect buttons
  gymsoWebsite/index.html
  gymsoWebsite/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#52 add home link for mobile screens in lioness project
  Lioness/css/styles.css
  Lioness/index.html
  Lioness/js/script.js
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#56 tilt-animation
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#59 Added back to top button in the GYMSO webpage
  gymsoWebsite/index.html
  gymsoWebsite/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#65 New Headphones Landing Page
  Headphones Website landing page/assets/css/styles.css
  Headphones Website landing page/assets/img/case.png
  Headphones Website landing page/assets/img/discount.png
  Headphones Website landing page/assets/img/favicon.png
  Headphones Website landing page/assets/img/home.png
  Headphones Website landing page/assets/img/logo.png
  Headphones Website landing page/assets/img/product1.png
  Headphones Website landing page/assets/img/product2.png
  Headphones Website landing page/assets/img/product3.png
  Headphones Website landing page/assets/img/product4.png
  Headphones Website landing page/assets/img/product5.png
  Headphones Website landing page/assets/img/specs.png
  Headphones Website landing page/assets/img/sponsor1.png
  Headphones Website landing page/assets/img/sponsor2.png
  Headphones Website landing page/assets/img/sponsor3.png
  Headphones Website landing page/assets/img/sponsor4.png
  Headphones Website landing page/assets/js/main.js
  Headphones Website landing page/assets/scss/base/_base.scss
  Headphones Website landing page/assets/scss/components/_buttons.scss
  Headphones Website landing page/assets/scss/components/_case.scss
  Headphones Website landing page/assets/scss/components/_discount.scss
  Headphones Website landing page/assets/scss/components/_footer.scss
  Headphones Website landing page/assets/scss/components/_header.scss
  Headphones Website landing page/assets/scss/components/_home.scss
  Headphones Website landing page/assets/scss/components/_mediaqueries.scss
  Headphones Website landing page/assets/scss/components/_products.scss
  Headphones Website landing page/assets/scss/components/_scroll.scss
  Headphones Website landing page/assets/scss/components/_specs.scss
  Headphones Website landing page/assets/scss/components/_sponsor.scss
  Headphones Website landing page/assets/scss/config/_variables.scss
  Headphones Website landing page/assets/scss/layout/_layout.scss
  Headphones Website landing page/assets/scss/styles.scss
  Headphones Website landing page/index.html
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#57 [project- My Portfolio] navbar update
  Portfolio/bars-solid.svg
  Portfolio/index.html
  Portfolio/script.js
  Portfolio/style.css
  Portfolio/xmark-solid.svg
Labels: help wanted, hacktoberfest2023, hacktoberfest-accepted

#68 alignment of image done
  CodeBuddy/src/index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#72 Added Portfolio Website
  Portfolio_HP/hp.png
  Portfolio_HP/index.html
  Portfolio_HP/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#64 add responsive landing page #63
  Adventure Landing Page/img/background.png
  Adventure Landing Page/img/favicon.ico
  Adventure Landing Page/img/favicon.png
  Adventure Landing Page/img/foreground.png
  Adventure Landing Page/img/sport-1.jpg
  Adventure Landing Page/img/sport-2.jpg
  Adventure Landing Page/img/sport-3.jpg
  Adventure Landing Page/index.html
  Adventure Landing Page/style.css
  Responsive Ecommerce Landing Page/image/1.webp
  Responsive Ecommerce Landing Page/image/2.webp
  Responsive Ecommerce Landing Page/image/3.webp
  Responsive Ecommerce Landing Page/image/4.webp
  Responsive Ecommerce Landing Page/image/5.webp
  Responsive Ecommerce Landing Page/image/6.jpg
  Responsive Ecommerce Landing Page/image/7.webp
  Responsive Ecommerce Landing Page/image/8.webp
  Responsive Ecommerce Landing Page/image/Appstore.png
  Responsive Ecommerce Landing Page/image/cart.svg
  Responsive Ecommerce Landing Page/image/home.png
  Responsive Ecommerce Landing Page/image/icon.png
  Responsive Ecommerce Landing Page/image/playstore.png
  Responsive Ecommerce Landing Page/image/profile.svg
  Responsive Ecommerce Landing Page/index.html
  Responsive Ecommerce Landing Page/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#79 [Book Store Landing Page] enhance responsiveness
  Books_store_LandingPage/script.js
  Books_store_LandingPage/styles.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#86 responsiveness made
  EarWorms/contact.css
  EarWorms/contact.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#95 Landing Page complete
  CryptoQuasarX/img/homepage.png
  CryptoQuasarX/img/iPhone 13 Pro model.png
  CryptoQuasarX/img/iphone-tilt.png
  CryptoQuasarX/img/table.png
  CryptoQuasarX/index.html
  CryptoQuasarX/styles.css
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#89 add modern chair project #87
  Modern Chair Project/.vscode/settings.json
  Modern Chair Project/README.md
  Modern Chair Project/images/chair1.png
  Modern Chair Project/images/chair2.png
  Modern Chair Project/images/chair3.png
  Modern Chair Project/images/chair4.png
  Modern Chair Project/images/chair5.png
  Modern Chair Project/images/chair6.png
  Modern Chair Project/images/color1.jpg
  Modern Chair Project/images/color2.jpg
  Modern Chair Project/images/color3.jpg
  Modern Chair Project/images/color4.jpg
  Modern Chair Project/images/color5.jpg
  Modern Chair Project/images/color6.jpg
  Modern Chair Project/images/favicon.ico
  Modern Chair Project/index.html
  Modern Chair Project/style.css
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#97 feat: landing page and gitignore added
  .gitignore
  index.html
  responsive-landing-page/app.js
  responsive-landing-page/img/logo.png
  responsive-landing-page/img/person.png
  responsive-landing-page/img/shape.png
  responsive-landing-page/index.html
  responsive-landing-page/style.css
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted

#102 DesignMaker-HacktoberFest
  DesignMaker-Hacktober/Index.html
  DesignMaker-Hacktober/style.css
  index.html
Labels: hacktoberfest, hacktoberfest2023, hacktoberfest-accepted
